abstract ChessPieceBase {
    - number positionX
    - number positionY
    - string chessType
    + ChessPieceBase(number x, number y, string type)
    + function checkMove()
    + function setType()
}


class King {
    + checkMove()
    + setType()
}

class Queen {
    + checkMove()
    + setType()
}

class Bishop {
    + checkMove()
    + setType()
}

class Knight {
    + checkMove()
    + setType()
}

class Rook {
    + checkMove()
    + setType()
}   

class Pawn {
    + checkMove()
    + setType()
}

ChessPieceBase <|-- King
ChessPieceBase <|-- Queen
ChessPieceBase <|-- Bishop
ChessPieceBase <|-- Knight
ChessPieceBase <|-- Rook
ChessPieceBase <|-- Pawn



abstract BoardBase {
    - ChessPieceBase[] pieces
    + BoardBase()
    + function addPiece()
    + function removePiece()
    + function movePiece()
}

class ChessBoard {
    + addPiece()
    + removePiece()
    + movePiece()
}

BoardBase <|-- ChessBoard

abstract PlayerBase {
    - string name
    - string color
    - BoardBase board
    + PlayerBase(string name, string color)
    + function joinGame()
    + function movePiece()
    + function choosePiece()
    + function chooseMove()
    + function endGame()
    + function outGame()
    + function storeHistoryMove()
}

class PlayerBlack {
    + joinGame()
    + movePiece()
    + choosePiece()
    + chooseMove()
    + endGame()
    + outGame()
    + storeHistoryMove()
}

class PlayerWhite {
    + joinGame()
    + movePiece()
    + choosePiece()
    + chooseMove()
    + endGame()
    + outGame()
    + storeHistoryMove()
}

PlayerBase <|-- PlayerBlack
PlayerBase <|-- PlayerWhite

PlayerBlack -> ChessBoard
PlayerWhite -> ChessBoard


abstract GameBase {
    - PlayerBase[] players
    - BoardBase board
    + GameBase()
    + function startGame()
    + function endGame()
    + function storeHistoryMove()
}

class ChessGame {
    + startGame()
    + endGame()
    + storeHistoryMove()
}

GameBase <|-- ChessGame

ChessGame -> PlayerBlack
ChessGame -> PlayerWhite
ChessGame -> ChessBoard